#Server Portserver:  port: 9090#DataSource Proeprtiesspring:  datasource:    url: jdbc:h2:mem:testDB    username: azhar    password:     driver-class-name: org.h2.Driver#View Resolver  mvc:    view:      prefix: /views/      suffix: .jsp

 